# Move a folder up with, /dashboard, /api, and /nging_conf in the folder
version: "3.7"
services:
  foundry_dashboard:
    image: kenishi86/foundry-dashboard:latest
    container_name: foundry_dashboard
    restart: "unless-stopped"

    volumes: 
      - "./nginx_conf/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx_conf/.htpasswds:/etc/nginx/.htpasswds:ro"
    ports:
      - "33000:33000"
    
  foundry_dashboard_api:
    image: kenishi86/foundry-dashboard-api:latest
    container_name: foundry_dashboard_api
    init: true
    restart: "unless-stopped"

    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"

    environment:
      - LISTEN_PORT=45321
    
    ports:
      - "127.0.0.1:45321:45321"
